= docent CLI Reference
:revdate: 2026-05-01
:app-name: docent
:toc: auto
:sectanchors:
:sectlinks:
:doctype: book

== Overview

Documentation linter for Zig projects

== Usage

[source,sh]
----
docent [OPTIONS] <COMMAND> <paths>...
----

== Arguments

`<paths>...`::
Files or directories to lint +
Required: no +
Variadic: yes


== Options

`-r, --rule <rule>=<severity>`::
Override severity: \<name\>=\<allow|warn|deny|forbid\> +
Required: no +
Possible values: allow, warn, deny, forbid +
Scope: local

`--all <VALUE>`::
The level to apply to all rules. +
Required: no +
Possible values: warn, deny +
Scope: local

`-f, --format <VALUE>`::
The output format of the lints. +
Required: no +
Default: `pretty` +
Possible values: pretty, text, minimal, json +
Scope: local

`--include-build-scripts`::
Include build.zig and build/*.zig files in lint targets. +
Required: no +
Default: `false` +
Scope: local

`-h, --help`::
Print help. +
Required: no +
Scope: built-in

== Command Index

* xref:cmd-docent[`docent`] - Documentation linter for Zig projects
  ** xref:cmd-docent-docs[`docent docs`] - Generate AsciiDoc documentation for this CLI
  ** xref:cmd-docent-completion[`docent completion`] - Generate shell completion scripts
  ** xref:cmd-docent-help[`docent help`] - Print this message or the help of the given subcommand(s)


== Command Reference

[#cmd-docent]
=== `docent`

Documentation linter for Zig projects

==== Usage

[source,sh]
----
docent [OPTIONS] <COMMAND> <paths>...
----

==== Arguments

`<paths>...`::
Files or directories to lint +
Required: no +
Variadic: yes


==== Options

`-r, --rule <rule>=<severity>`::
Override severity: \<name\>=\<allow|warn|deny|forbid\> +
Required: no +
Possible values: allow, warn, deny, forbid +
Scope: local

`--all <VALUE>`::
The level to apply to all rules. +
Required: no +
Possible values: warn, deny +
Scope: local

`-f, --format <VALUE>`::
The output format of the lints. +
Required: no +
Default: `pretty` +
Possible values: pretty, text, minimal, json +
Scope: local

`--include-build-scripts`::
Include build.zig and build/*.zig files in lint targets. +
Required: no +
Default: `false` +
Scope: local

`-h, --help`::
Print help. +
Required: no +
Scope: built-in

==== Subcommands

* xref:cmd-docent-docs[`docent docs`] - Generate AsciiDoc documentation for this CLI
* xref:cmd-docent-completion[`docent completion`] - Generate shell completion scripts
* xref:cmd-docent-help[`docent help`] - Print this message or the help of the given subcommand(s)


[#cmd-docent-docs]
=== `docent docs`

Generate AsciiDoc documentation for this CLI

Parent: xref:cmd-docent[`docent`]

==== Usage

[source,sh]
----
docent docs [OPTIONS]
----

==== Options

`--output-dir <STRING>`::
Directory where AsciiDoc documentation is written. +
Required: no +
Default: `docs` +
Scope: local

`--file <STRING>`::
Output AsciiDoc file name. +
Required: no +
Default: `cli.adoc` +
Scope: local

`--template <STRING>`::
Optional custom Trama template path. +
Required: no +
Scope: local

`-h, --help`::
Print help. +
Required: no +
Scope: built-in


[#cmd-docent-completion]
=== `docent completion`

Generate shell completion scripts

Parent: xref:cmd-docent[`docent`]

==== Usage

[source,sh]
----
docent completion [OPTIONS] <shell>
----

==== Arguments

`<shell>`::
Target shell. +
Required: yes +
Variadic: no
 +
Possible values: bash, zsh, fish, pwsh, nu

==== Options

`-h, --help`::
Print help. +
Required: no +
Scope: built-in


[#cmd-docent-help]
=== `docent help`

Print this message or the help of the given subcommand(s)

Parent: xref:cmd-docent[`docent`]

==== Usage

[source,sh]
----
docent help [COMMAND]...
----


